[settings]
experimental = true

[tools]
starship = "latest"
uv = "latest"
"eza" = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
pi = "latest"
herdr = "latest"
zoxide = "latest"

[tools.opencode]
version = "latest"

[tools.rtk]
version = "latest"
postinstall = '''
rtk init -g --opencode
rtk init -g --agent pi
'''
