[settings]
experimental = true

[tools]
starship = "latest"
eza = "latest"

[tools.opencode]
version = "latest"

[tools."github:rtk-ai/rtk"]
version = "latest"
post_install = "rtk --init -g --opencode"
