[settings]
experimental = true

[tools]
starship = "latest"
uv = "latest"
"eza" = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
pi = "latest"
zoxide = "latest"

[tools.opencode]
version = "latest"

[tools."github:rtk-ai/rtk"]
version = "latest"
postinstall = '''
#!/bin/bash
set -e
rtk init -g --opencode
rtk init -g --agent pi
'''
